[package]
name = "mane_transcript_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
flate2 = "1.0.35"
reqwest = {version = "0.12.9", features = ["blocking", "json"]}
